// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHpWdkry2z7R472WKc5eITDEIvlpLYW1Q',
    appId: '1:33939497223:web:f94bbe17bc0acaef64e5a2',
    messagingSenderId: '33939497223',
    projectId: 'artportfolio-153f3',
    authDomain: 'artportfolio-153f3.firebaseapp.com',
    storageBucket: 'artportfolio-153f3.appspot.com',
    measurementId: 'G-WWK8J8J7B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWticzEq8rkZtKkABwguLUrqjmgt9wBmE',
    appId: '1:33939497223:android:c086684c1150198f64e5a2',
    messagingSenderId: '33939497223',
    projectId: 'artportfolio-153f3',
    storageBucket: 'artportfolio-153f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSicsPNCQry_qq4UIcZU4pGZ5ZmgH5Xm4',
    appId: '1:33939497223:ios:1eb922959c55806164e5a2',
    messagingSenderId: '33939497223',
    projectId: 'artportfolio-153f3',
    storageBucket: 'artportfolio-153f3.appspot.com',
    iosBundleId: 'com.example.artportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSicsPNCQry_qq4UIcZU4pGZ5ZmgH5Xm4',
    appId: '1:33939497223:ios:1eb922959c55806164e5a2',
    messagingSenderId: '33939497223',
    projectId: 'artportfolio-153f3',
    storageBucket: 'artportfolio-153f3.appspot.com',
    iosBundleId: 'com.example.artportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHpWdkry2z7R472WKc5eITDEIvlpLYW1Q',
    appId: '1:33939497223:web:038a4df98bd07a7c64e5a2',
    messagingSenderId: '33939497223',
    projectId: 'artportfolio-153f3',
    authDomain: 'artportfolio-153f3.firebaseapp.com',
    storageBucket: 'artportfolio-153f3.appspot.com',
    measurementId: 'G-NS3FHCGLXV',
  );
}
