// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABa5-uGi6WKYhf4zJ2JsCyfGllBiqZrm8',
    appId: '1:391361219183:web:46e4823c58b868ea239b9a',
    messagingSenderId: '391361219183',
    projectId: 'airbnb-ce515',
    authDomain: 'airbnb-ce515.firebaseapp.com',
    databaseURL: 'https://airbnb-ce515.firebaseio.com',
    storageBucket: 'airbnb-ce515.appspot.com',
    measurementId: 'G-7Y3CZFPZRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWyAsh-cPXQFihQAZ7UTL-xWw3QWu99JM',
    appId: '1:391361219183:android:f8b218644569378a239b9a',
    messagingSenderId: '391361219183',
    projectId: 'airbnb-ce515',
    databaseURL: 'https://airbnb-ce515.firebaseio.com',
    storageBucket: 'airbnb-ce515.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBJDuyIz0N0t3SoTBkiw013Rt1VhZUbpg',
    appId: '1:391361219183:ios:3c850f8c9346d280239b9a',
    messagingSenderId: '391361219183',
    projectId: 'airbnb-ce515',
    databaseURL: 'https://airbnb-ce515.firebaseio.com',
    storageBucket: 'airbnb-ce515.appspot.com',
    iosBundleId: 'com.example.artPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBJDuyIz0N0t3SoTBkiw013Rt1VhZUbpg',
    appId: '1:391361219183:ios:3b49afb96c2be714239b9a',
    messagingSenderId: '391361219183',
    projectId: 'airbnb-ce515',
    databaseURL: 'https://airbnb-ce515.firebaseio.com',
    storageBucket: 'airbnb-ce515.appspot.com',
    iosBundleId: 'com.example.artPortfolio.RunnerTests',
  );
}
